# Generated by Django 2.1.5 on 2019-01-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190122_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('gene2intervals', models.TextField()),
                ('interval2genes', models.TextField()),
                ('interval2blocks', models.TextField()),
                ('created_by', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('track_sources', models.TextField()),
                ('created_by', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneModel',
        ),
    ]
