# Generated by Django 2.1.5 on 2019-01-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190122_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='access',
            field=models.CharField(default='public', max_length=128),
        ),
    ]
