# Generated by Django 2.1.5 on 2019-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190130_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('type', models.CharField(max_length=32)),
                ('version', models.TextField(blank=True, default=None, null=True)),
                ('organism', models.TextField(blank=True, default=None, null=True)),
                ('reference_model', models.IntegerField(blank=True, default=None, null=True)),
                ('created_by', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='reference_model',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='version',
        ),
        migrations.RemoveField(
            model_name='savedview',
            name='track_sources',
        ),
        migrations.AddField(
            model_name='savedview',
            name='data_bundle_source',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
