# Generated by Django 2.1.5 on 2019-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_datamodelbundle_data_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='data_model_bundle',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
