# Generated by Django 2.1.5 on 2019-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_datamodel_data_model_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='data_model_bundle',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
