# Generated by Django 2.1.5 on 2019-01-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190131_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodelbundle',
            name='chromosome_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
