# Generated by Django 2.1.5 on 2019-01-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_datamodelbundle_chromosome_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodelbundle',
            name='biotype',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
