# Generated by Django 2.1.5 on 2019-02-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190201_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='gene2info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
