# Generated by Django 2.1.5 on 2019-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_datamodel_rainbow2gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodelbundle',
            name='global_gene2info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
