# Generated by Django 2.1.5 on 2019-03-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_datamodelbundle_global_gene2info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(blank=True, default=None, null=True)),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('short_name', models.TextField()),
                ('description', models.TextField()),
                ('mapping', models.TextField()),
                ('version', models.TextField(blank=True, default=None, null=True)),
                ('organism', models.TextField(blank=True, default=None, null=True)),
                ('reference_model', models.IntegerField(blank=True, default=None, null=True)),
                ('created_by', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
