# Generated by Django 2.1.5 on 2019-03-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='access',
            field=models.CharField(default='public', max_length=128),
        ),
    ]
